#!/usr/bin/perl -w

use strict;


my ($modeIndex, $modelIndex);

for ($modeIndex = 7; $modeIndex <= 11; $modeIndex = $modeIndex + 1)
    for ($modelIndex = 1; $modelIndex <= 11; $modelIndex = $modelIndex + 1)
{
    {
	print STDOUT "ReadPdb $modeIndex.$modelIndex\n";
    }
}

